---
- hosts: all
  name: "Docker Container Create"
  tasks:
    - name: "Create Docker Image"
      docker_image:
        name: nginx
        source: pull
    - name: " Run container"
      docker_container:
         name: webcon
         image: nginx
         state: present
         interactive: yes
         tty: yes
         detach: yes
         ports:
         - "8005:80"
