---
- hosts: all
  become: True
  tasks:
    - name: Install apache packages
      apt:
        name: apache2
        state: "present"
    - name: "copy"
      copy: 
        content: "New Ansible Test WebPage Latest"
        dest: /var/www/html/index.html
    - name: Service start
      service:
        name: apache2
        state: started
        
    
